apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-flask-app
  labels:
    app: mon-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon-flask-app
  template:
    metadata:
      labels:
        app: mon-flask-app
    spec:
      containers:
        - name: mon-flask-app
          image: quentinhemeryck/mon-flask-app:60e4f1b6163ef3c6943f86d8b36fdb5038af1690
          imagePullPolicy: IfNotPresent
